### ISSUE TITLE
airQualitySensor PM2.5 via mqtt

### ISSUE THREAD

**Issue by pawelosin** [arachnetech/homebridge-mqttthing#132]
What is the correct topic for the airQualitySensor PM2.5. I am using SDS0X1 sensor connected to Wemos d1 mini with tasmota. Result to PM10 is correct, but when i typed the topic for PM2.5 the homebridge returns problem: 
[2019-6-19 19:52:53] [AirQuality] MQTT options: {"keepalive":10,"clientId":"mqttthing_AirQuality_f7d7e5b3","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"rejectUnauthorized":false}
[2019-6-19 19:52:54] SyntaxError: Unexpected number
    at Function (<anonymous>)
    at mqttSubscribe (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:96:31)
    at floatCharacteristic (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1030:13)
    at characteristic_PM2_5Density (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1651:9)
    at createServices (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:2322:17)
    at new makeThing (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:2506:20)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[2019-6-19 19:52:54] Got SIGTERM, shutting down Homebridge...

My config.json file is  
...
"getPM2_5Density": {
"topic": "tele/sonoff/SENSOR",
"apply": "return JSON.parse(message).SDS0X1.PM2.5"
},...
Sorry for my English

**Comment by tobekas** [comment]
JSON.parse(message).SDS0X1.**PM2.5** is no valid syntax. Maybe it has to be PM2_5?

**Comment by pawelosin** [comment]
I had tried this but it doesn’t work.

**Comment by tobekas** [comment]
Try JSON.parse(message).SDS0X1['PM2.5']

**Comment by pawelosin** [comment]
Now it works fine. Thanks!
