### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:

### ISSUE THREAD

**Issue by pbriesch** [arachnetech/homebridge-mqttthing#17]
Hi,

I have two topics from the same device (ESPURNA-192102 with SHT30 sensor) and I get the above mentioned error. 

How should I change my configuration file?

**Here is the config**

{
            "accessory": "mqttthing",
            "type": "humiditySensor",
            "name": "SHT30",
            "caption": "Humidity",
            "url": "",
            "username": "",
            "password": "",
            "topics": {
                "getCurrentRelativeHumidity": "ESPURNA-192102/humidity",
                "getStatusActive": "ESPURNA-192102/status",
                "getStatusFault": "",
                "getStatusTampered": "",
                "getStatusLowBattery": ""
            }
        },
  {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "SHT30",
            "caption": "Temperature",
            "url": "",
            "username": "",
            "password": "",
            "topics": {
                "getCurrentRelativeHumidity": "ESPURNA-192102/temperature",
                "getStatusActive": "ESPURNA-192102/status",
                "getStatusFault": "",
                "getStatusTampered": "",
                "getStatusLowBattery": ""
            }
        },

**Here is the error message:**

[2018-9-4 01:36:17] [SHT30] Initializing mqttthing accessory...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
            ^
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9cb50972-5af3-4559-a7f8-1eacf979fae4
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:300:18)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
Stopped Node.js HomeKit Server.

**Comment by arachnetech** [comment]
I suspect you need different names for your two (from Homekit’s perspective) devices.

**Comment by pbriesch** [comment]
Well, I could try the IP for the second topic. I will test this.

However, this won't work if there were 3 topics coming from one device...

**Comment by pbriesch** [comment]
Using the IP did not work. The UUID ist still the same.

**Comment by arachnetech** [comment]
I thought the issue was your `"name": "SHT30"` settings, because this is set to the same in both. The name is only used as your identifier in homekit - it doesn't need to match a hostname or IP address.

Does it work if you comment out one of the accessories temporarily?

**Comment by arachnetech** [comment]
It should be fine to use the same topic for `"getStatusActive": "ESPURNA-192102/status",` are you have.

**Comment by pbriesch** [comment]
The issue was actually the name "SHT30" which I used two times. I'm using now two different names and both readings show up, albeit the temperature reading is 0. Now I need to figure this out.

Thanks!
