### ISSUE TITLE
upgraded version crashes during inititalization

### ISSUE THREAD

**Issue by cbrandlehner** [arachnetech/homebridge-mqttthing#187]
```
[37m[12/31/2019, 4:02:06 PM][39m [36m[Z1][39m Initializing mqttthing accessory...
[37m[12/31/2019, 4:02:06 PM][39m [1m[31mTypeError: Cannot read property 'CurrentConsumption' of undefined
    at characteristic_CurrentConsumption (/homebridge/node_modules/homebridge-mqttthing/index.js:1806:62)
    at createServices (/homebridge/node_modules/homebridge-mqttthing/index.js:2116:17)
    at new makeThing (/homebridge/node_modules/homebridge-mqttthing/index.js:2594:20)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)[39m[22m
```

**Comment by Scialla** [comment]
i've problem too, my Homebridge crash and no start anymore.
i'd must downgrade to previous version to resolve

**Comment by arachnetech** [comment]
Thanks - what a pain. Apologies. The changes in this build were (I thought) very minor, and I haven't installed the new build on my own homebridge yet.

I suspect this is related to my change of the fakegato dependency version for issue #178...

**Comment by arachnetech** [comment]
I'm struggling to reproduce this.

**Comment by arachnetech** [comment]
The newest homebridge-lib seems to be incompatible with Eve history (fakegato) support added by @tobekas. For now I've just reverted to an older homebridge-lib. I believe the latest release will work.

**Comment by tobekas** [comment]
Seems that `Eve.Characteristic` is undefined and must be replaced by `Eve.Characteristics` since homebridge-lib v4.3.1
Same for `Eve.Service` -> `Eve.Services`

**Comment by arachnetech** [comment]
Aha, thanks. I will see if that will fix it with the latest homebridge-lib.

**Comment by arachnetech** [comment]
Done now.
