### ISSUE TITLE
Thermostat accessory TargetHumidty issue

### ISSUE THREAD

**Issue by JustAmaze** [arachnetech/homebridge-mqttthing#378]
Hi,

first of all thank you so much for this great and usefull plugin. Really appriciate !! I have a little problem with thermostat accessory while implement to communicate with my home made thermostat. Every item is working wonderfully except one item. If i assign any mqtt topic to "Target Relative Humidity", i can not connect via homekit. and dissepears from iphone screen. Accessory log output as below. Pls assist if there is an anyway to fix  

[23/12/2020, 21:01:26] [Termostat] Exception while creating services: TypeError: Cannot read property 'on' of undefined
[23/12/2020, 21:01:27] [Termostat] TypeError: Cannot read property 'on' of undefined
    at floatCharacteristic (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1033:24)
    at characteristic_TargetRelativeHumidity (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1378:17)
    at configToServices (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:2786:21)
    at createServices (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:2981:24)
    at new makeThing (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:3013:23)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
[23/12/2020, 21:01:27] [Termostat] Accessory mqttthing returned empty set of services. Won't adding it to the bridge!

**Comment by arachnetech** [comment]
If you could share your configuration, I'll try to reproduce the issue...

**Comment by JustAmaze** [comment]
Sure. Pls find here below;

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:4E:15:0C:A6:D4",
        "port": 51904,
        "pin": "977-83-716"
    },
    "accessories": [
        {
            "type": "thermostat",
            "name": "Termostat",
            "url": "192.168.0.8:1883",
            "topics": {
                "getCoolingThresholdTemperature": "/termostat/espSogutmaEsik",
                "setCoolingThresholdTemperature": "/termostat/homekitSogutmaEsik",
                "getCurrentHeatingCoolingState": "/termostat/espIsitiliyorSogutuluyor",
                "getCurrentRelativeHumidity": "/termostat/espnem",
                "getCurrentTemperature": "/termostat/espSicaklik",
                "getHeatingThresholdTemperature": "/termostat/espIsitmaEsik",
                "setHeatingThresholdTemperature": "/termostat/homekitIsitmaEsik",
                "getTargetHeatingCoolingState": "/termostat/espDurumu",
                "setTargetHeatingCoolingState": "/termostat/homekitDurumu",
                "getTargetTemperature": "/termostat/espHedefSicaklik",
                "setTargetTemperature": "/termostat/homekitHedefSicaklik"
            },
            "confirmationPeriodms": 1500,
            "whiteMix": true,
            "accessory": "mqttthing"
        },
        {
            "type": "motionSensor",
            "name": "Hareket Sensörü",
            "url": "192.168.0.8:1883",
            "topics": {
                "getMotionDetected": "/salon/hareket/data"
            },
            "whiteMix": true,
            "accessory": "mqttthing"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ]
}

**Comment by arachnetech** [comment]
Thanks. Target relative humidity should now be working in version 1.1.23.
