### ISSUE TITLE
Homebridge 1.3 beta Error: characteristic value...

### ISSUE THREAD

**Issue by rbswift** [arachnetech/homebridge-mqttthing#394]
Using beta 1.3 version 44 I get these new errors that were not present in version 1.2.5

```
Jan 17 17:50:53 pi4 homebridge[2935]: [1/17/2021, 5:50:53 PM] Received warning for the plugin 'homebridge-mqttthing' from the characteristic 'Target Heater-Cooler State': Unhandled error thrown inside read handler for characteristic: Error: characteristic value 0 is not contained in valid values array!
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1958:15)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1428:24
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
Jan 17 17:50:53 pi4 homebridge[2935]:     at handleGetStateCallback (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:246:21)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1107:25)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.emit (events.js:314:20)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1404:14
Jan 17 17:50:53 pi4 homebridge[2935]:     at new Promise (<anonymous>)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1402:12)
Jan 17 17:50:53 pi4 homebridge[2935]:     at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
Jan 17 17:50:53 pi4 homebridge[2935]:     at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
Jan 17 17:50:53 pi4 homebridge[2935]:     at new Promise (<anonymous>)
Jan 17 17:50:53 pi4 homebridge[2935]:     at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:590:24)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2057:22)
Jan 17 17:50:53 pi4 homebridge[2935]: [Bedroom Air Conditioner@Bedroom Air Conditioner@Target Heater-Cooler State] Unhandled error thrown inside read handler for characteristic: Error: characteristic value 0 is not contained in valid values array!
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1958:15)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1428:24
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
Jan 17 17:50:53 pi4 homebridge[2935]:     at handleGetStateCallback (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:246:21)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1107:25)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.emit (events.js:314:20)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1404:14
Jan 17 17:50:53 pi4 homebridge[2935]:     at new Promise (<anonymous>)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1402:12)
Jan 17 17:50:53 pi4 homebridge[2935]:     at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
Jan 17 17:50:53 pi4 homebridge[2935]:     at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
Jan 17 17:50:53 pi4 homebridge[2935]:     at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
Jan 17 17:50:53 pi4 homebridge[2935]:     at new Promise (<anonymous>)
Jan 17 17:50:53 pi4 homebridge[2935]:     at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:590:24)
Jan 17 17:50:53 pi4 homebridge[2935]:     at TargetHeaterCoolerState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2057:22)
Jan 17 17:50:53 pi4 homebridge[2935]: [1/17/2021, 5:50:53 PM] Received warning for the plugin 'homebridge-mqttthing' from the characteristic 'Swing Mode': characteristic was supplied illegal value: undefined! This might throw errors in the future!
Jan 17 17:50:53 pi4 homebridge[2935]: [Bedroom Air Conditioner@Bedroom Air Conditioner@Swing Mode] characteristic was supplied illegal value: undefined! This might throw errors in the future!
Jan 17 17:50:53 pi4 homebridge[2935]: [1/17/2021, 5:50:53 PM] Received warning for the plugin 'homebridge-mqttthing' from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 17.
Jan 17 17:50:53 pi4 homebridge[2935]: [Heating@Heating@Current Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 17.
```

config:

```
        {
            "accessory": "mqttthing",
            "type": "heaterCooler",
            "name": "Bedroom Air Conditioner",
            "logMqtt": true,
            "targetHeaterCoolerValues": [
                "Auto",
                "Heat",
                "Cool"
            ],
            "swingModeValues": [
                "Off",
                "On"
            ],
            "restrictHeaterCoolerState": [
                1,
                2
            ],
            "topics": {
                "setActive": "cmnd/bedroomirblaster/IRHVAC",
                "setTargetHeaterCoolerState": "cmnd/bedroomirblaster/IRHVAC",
                "setCoolingThresholdTemperature": "cmnd/bedroomirblaster/IRHVAC",
                "setHeatingThresholdTemperature": "cmnd/bedroomirblaster/IRHVAC",
                "setSwingMode": "cmnd/bedroomirblaster/IRHVAC",
                "setRotationSpeed": "cmnd/bedroomirblaster/IRHVAC",
                "getCurrentTemperature": {
                    "topic": "zigbee2mqtt/sonofftemperature",
                    "apply": "return (Math.round(message*2)/2);"
                }
            },
            "codec": "json",
            "jsonCodec": {
                "fixed": {
                    "Vendor": "FUJITSU_AC",
                    "Model": "3",
                    "Celsius": "On",
                    "Quiet": "On",
                    "Turbo": "Off",
                    "Econo": "Off",
                    "FanSpeed": "Lowest"
                },
                "properties": {
                    "active": "Power",
                    "targetHeaterCoolerState": "Mode",
                    "coolingThresholdTemperature": "Temp",
                    "heatingThresholdTemperature": "Temp",
                    "swingMode": "SwingV",
                    "currentTemperature": "temperature"
                },
                "retain": true
            }
        },
        {
            "accessory": "mqttthing",
            "type": "thermostat",
            "name": "Heating",
            "mqttPubOptions": {
                "retain": true
            },
            "topics": {
                "getCurrentHeatingCoolingState": "heating/getCurrentHeatingCoolingState",
                "setTargetHeatingCoolingState": "heating/setTargetHeatingCoolingState",
                "getTargetHeatingCoolingState": "heating/getTargetHeatingCoolingState",
                "getCurrentTemperature": {
                    "topic": "tele/thermostat/SENSOR",
                    "apply": "return (Math.round(JSON.parse(message).BME280.Temperature*2)/2);"
                },
                "setTargetTemperature": "heating/setTargetTemperature",
                "getTargetTemperature": "heating/getTargetTemperature"
            },
            "minTemperature": 17,
            "maxTemperature": 25,
            "restrictHeatingCoolingState": [
                0,
                1
            ],
            "logMqtt": true
        },
```

**Comment by rbswift** [comment]
Hi @arachnetech could I please ask you to have a look at this? Homebridge 1.3 is released now and I can no longer get the codec functionality to work. This config worked fine in earlier versions. I'm not really sure what to look for. Thanks!

**Comment by rbswift** [comment]
I think homebridge 1.3.1 fixed this
