### ISSUE TITLE
Can't get MQTTThing running

### ISSUE THREAD

**Issue by jeroen020** [arachnetech/homebridge-mqttthing#408]
Hi, trying to install via the UI and have the following config:

```
{
            "type": "fan",
            "name": "Itho Ventilatie",
            "logMqtt": true,
            "topics": {
                "getRotationSpeed": "itho/cmd/get/currentspeed",
                "setRotationSpeed": "itho/cmd/speed"
            },
            "accessory": "mqttthing"
        }
```

I get the following error in the status log:

```
Error: The requested accessory 'mqttthing' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Mosquitto is running on the same Pi as Homebridge.
All my other Plugins run without issue.
Any advice much appreciated.

**Comment by arachnetech** [comment]
It looks as if the plugin isn't installed, for some reason. Do you see mqttthing in the output from `npm -g list --depth=0` ?
