### ISSUE TITLE
Voltage: supplied illegal value 

### ISSUE THREAD

**Issue by fgrosswig** [arachnetech/homebridge-mqttthing#463]
How this can be fixed? my arduino sends this voltage state and i like to display this value.
```
[homebridge-mqttthing] This plugin generated a warning from the characteristic 'Voltage': characteristic was supplied illegal value: number 4.28 exceeded minimum of 100. See https://git.io/JtMGR for more info.
```

**Comment by iandronowicz** [comment]
same problem:

[11/21/2021, 3:59:29 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Voltage': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.

**Comment by arachnetech** [comment]
It appears that this property isn't expected to go below 100. It may be possible to extend the range. I'll investigate.

**Comment by wumpsven** [comment]
Same here with Gosund SP111 v1.4 Tasmota 10.0.0.3

**Comment by eXCepT74** [comment]
Hello
Any progress ? 

i changed value 100 to 0 in:

floatCharacteristic( service, 'voltage', Eve.Characteristics.Voltage, null, config.topics.getVolts, 100 );

but it not changed anything.
Any idea how to fix?

**Comment by eXCepT74** [comment]
> How this can be fixed? my arduino sends this voltage state and i like to display this value. Seems a fixed value of 100 which isnt met due the minimum value?
> 
> `[ESP2688 Battery] Ignoring invalid value [4.44] for Voltage - below minimum (100)`
> 
> `[homebridge-mqttthing] This plugin generated a warning from the characteristic 'Voltage': characteristic was supplied illegal value: number 4.44 exceeded minimum of 100. See https://git.io/JtMGR for more info.`
> 
> https://github.com/arachnetech/homebridge-mqttthing/blob/42c7a5da71b2a6d80d49d2e70016dd03db387c24/index.js#L2241
> 
> ```
>  Error:
>     at _Characteristics.<computed>.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
>     at _Characteristics.<computed>.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
>     at handleGetStateCallback (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:282:21)
>     at _Characteristics.<computed>.<anonymous> (/usr/local/lib/node_modules/homebridge-mqttthing/index.js:1174:21)
>     at _Characteristics.<computed>.emit (events.js:375:28)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
>     at new Promise (<anonymous>)
>     at _Characteristics.<computed>.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
> ```
> 
> Also the pressure gets invalid:
> 
> `Ignoring invalid value [989.51] for Air Pressure - not an integer`


I have same voltage , pressure and luminosity problem.

But air pressure is quite easy to fix if you use tasmota fw to get sensor result.
You can use rules to make it integer. I did like that and it helped me.

**Comment by arachnetech** [comment]
These validation messages are a pain!

It may be possible to lower the (default) homekit voltage minimum - which appears designed for mains voltages. I'll take a look.

**Comment by arachnetech** [comment]
I assume this is an outlet, as that's the only thing that supports voltage in mqttthing?

Trying to test with this config and the Eve app, but I can't see how to get the Eve app to display voltage?

```
        {
            "type": "outlet",
            "name": "Test Outlet",
            "url": "homebridge2",
            "topics": {
                "setOn": "test/outlet/on",
                "getWatts": "test/outlet/watts",
                "getVolts": "test/outlet/voltage"
            },
            "accessory": "mqttthing",
            "logMqtt": true
        }
```

**Comment by arachnetech** [comment]
I've added configurable voltage range in version 1.1.40 - please let me know if that helps.

```
        {
            "type": "outlet",
            "name": "Test Outlet",
            "url": "homebridge2",
            "topics": {
                "setOn": "test/outlet/on",
                "getInUse": "test/outlet/inuse",
                "getWatts": "test/outlet/watts",
                "getVolts": "test/outlet/voltage",
                "getAmperes": "test/outlet/amps"
            },
            "accessory": "mqttthing",
            "logMqtt": true,
            "minVolts": 1,
            "maxVolts": 25
        }
```

**Comment by iandronowicz** [comment]
I`ve set the minVolts to 100, no maxVolts, let´s see what happens

**Comment by eXCepT74** [comment]
> I assume this is an outlet, as that's the only thing that supports voltage in mqttthing?
> 
> Trying to test with this config and the Eve app, but I can't see how to get the Eve app to display voltage?
> 
> ```
>         {
>             "type": "outlet",
>             "name": "Test Outlet",
>             "url": "homebridge2",
>             "topics": {
>                 "setOn": "test/outlet/on",
>                 "getWatts": "test/outlet/watts",
>                 "getVolts": "test/outlet/voltage"
>             },
>             "accessory": "mqttthing",
>             "logMqtt": true
>         }
> ```

Hello.
To get voltage and as well current reading in Eve just touch finger lhside of switch area ( where you have switch description ) and when u get place where is chart of power usage then touch "edit" ( top-right ).
then u can enable voltage and current which is disabled by default.

**Comment by iandronowicz** [comment]
Well the minVolts 100 didn’t get rid of the warning.

this is my config file:

{
    "accessory": "mqttthing",
    "type": "outlet",
    "name": "Parrilla",
    "url": "x.x.x.x",
    "outletInUseBy": "getAmperes",
    "outletInUseCurrent": "0.01",
    "onValue": "ON",
    "offValue": "OFF",
    "minVolts": 100,
    "topics":
    {
        "getOn":                "stat/sonoffpow1/RESULT",
        "setOn":                "cmnd/sonoffpow1/POWER",
        "getInUse": {
                "topic": "tele/sonoffpow1/SENSOR",
                "apply": "return (JSON.parse(message).ENERGY.Power > 0) ? 'ON' : 'OFF'"
        },
                                "getWatts": {
                                        "topic": "tele/sonoffpow1/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Power;"
                                },
                                "getVolts": {
                                        "topic": "tele/sonoffpow1/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Voltage;"
                                },
                                "getAmperes": {
                                        "topic": "tele/sonoffpow1/SENSOR",
                                        "apply": "return JSON.parse(message).ENERGY.Current;"
                                }
    }

**Comment by eXCepT74** [comment]
I can't find mqttthing index.js in Hoobs4 package.
Anyone know where they located plugins folder ?

 I changed to Hoobs due to serious bug in Homebridge which stopped responding to IOS after 3-4 hours of work after restart HB stack.

**Comment by eXCepT74** [comment]
I getting that warning only if outlet is switched off - then voltage value is "0".
I tried to set "minvoltage" to "0" but still get same warning.

**Comment by fgrosswig** [comment]
Still the same obvious error:

```

13:16:12 raspberrypi homebridge[535]: [21.3.2022, 13:16:12] [ESP2688 Battery] Received MQTT: esp/bme280/battery = 4.40
Mar 21 13:16:12 raspberrypi homebridge[535]: [21.3.2022, 13:16:12] [ESP2688 Battery] Ignoring invalid value [4.4] for Voltage - below minimum (100)
```

```
{
            "type": "outlet",
            "name": "ESP2688 Battery",
            "url": "http://localhost:1883",
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getVolts": "esp/bme280/battery"
            },
            "minValue": "0",
            "maxValue": "250",
            "history": true,
            "accessory": "mqttthing"
        },
```

**Comment by arachnetech** [comment]
I wouldn't expect updating to touch your configuration. However, I'm also not aware of any update script.

**Comment by fgrosswig** [comment]
Hmmmm, ok - well don't want to stress it maybe I did that really by myself some days ago without remembering to 😅

**Comment by eXCepT74** [comment]
> Well the minVolts 100 didn’t get rid of the warning.
> 
> this is my config file:
> 
> { "accessory": "mqttthing", "type": "outlet", "name": "Parrilla", "url": "x.x.x.x", "outletInUseBy": "getAmperes", "outletInUseCurrent": "0.01", "onValue": "ON", "offValue": "OFF", "minVolts": 100, "topics": { "getOn": "stat/sonoffpow1/RESULT", "setOn": "cmnd/sonoffpow1/POWER", "getInUse": { "topic": "tele/sonoffpow1/SENSOR", "apply": "return (JSON.parse(message).ENERGY.Power > 0) ? 'ON' : 'OFF'" }, "getWatts": { "topic": "tele/sonoffpow1/SENSOR", "apply": "return JSON.parse(message).ENERGY.Power;" }, "getVolts": { "topic": "tele/sonoffpow1/SENSOR", "apply": "return JSON.parse(message).ENERGY.Voltage;" }, "getAmperes": { "topic": "tele/sonoffpow1/SENSOR", "apply": "return JSON.parse(message).ENERGY.Current;" } }

I will try your config but why options:

 "minVolts": 0,
 "maxVolts": 300

are not working ?  After it should be no error messages , right ?

**Comment by eXCepT74** [comment]
Anyway "minVolts" = "0"  is not working.

**Comment by arachnetech** [comment]
Bizarre. Allowed lower values without validation errors for me.
