### ISSUE TITLE
Maximum call stack size exceeded at shim-array.js

### ISSUE THREAD

**Issue by flok** [arachnetech/homebridge-mqttthing#517]
Since upgrading the plugin i get the following error when starting up homebridge

```
[25/12/2021, 18:25:25] RangeError: Maximum call stack size exceeded
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:30:5)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:31:22)
```

A downgrade of the version also doesn't fix the error above. Is there some temp file the plugin generates that maybe stops it from starting up?

No changes to config from it running to upgrading and starting it again. Downgraded all the way to 1.1.31 but error still persists.

**Comment by NorthernMan54** [comment]
Humm - Had a user of my plugin report the same, turns out it was a different plugin

https://github.com/NorthernMan54/homebridge-alexa/issues/481

**Comment by arachnetech** [comment]
Thanks, @NorthernMan54 - which plug-in is causing this (assuming it's not mqttthing either!)?

**Comment by NorthernMan54** [comment]
The rumour is myq

**Comment by flok** [comment]
for me it was homebridge-fritz (0.9.5) somehow, but that didnt get updated in a long time, maybe some changes inside homebridge itself broke that old plugin. Now using homebridge-fritz-platform and it works fine
