### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fearlesschicken** [arachnetech/homebridge-mqttthing#524]
This chunk pop up for a few times in a row when restarting homebridge and causes homebridge to crash and restart.  After that I see this again and homebridge stabilizes.  It might crash again when this chunk of error messages pops up again.

Error occurred handling incoming (on eth0) dns query packet: RangeError: Maximum call stack size exceeded
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:34:5)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)
	at Function.Array.from (/usr/local/lib/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22)

This happens on .38 and .37.  Currently downgraded to .36 to stop this from happening.

OS: Debian 11
Node: 16.13.1
Homebridge: 1.3.9

**Comment by NorthernMan54** [comment]
Please see #518 for more details and a workaround for this issue.

**Comment by fearlesschicken** [comment]
Ah, I see the workaround.  Thanks for the fast reply
