### ISSUE TITLE
JSON for tasmota ble - connected xiaomi LYWSD0290dd04

### ISSUE THREAD

**Issue by sommertrip** [arachnetech/homebridge-mqttthing#546]
Hi!

This is a request for help on the configuration, I don't think it's a bug.

I am very happily using homebridge with many devices over MQTT but I do have issues to get temperatur/humidity displayed fetched from a Xiaomi BLE Device.

I do have the following Setup:
- RasperryPi with 1.4.0
- Homebridge Mqttthing - 1.1.39
- Tasmota 32 BLE configured to receive data via MQTT 
Console report: 
<img width="1413" alt="CleanShot 2022-03-14 at 10 53 53@2x" src="https://user-images.githubusercontent.com/15965995/158148595-7c0bdf92-c558-4120-87d2-10928437462c.png">

I´d like to get the temperture and humidity displayed in homekit apps. 
the current JSON in homebridge in the temp section is.
<img width="658" alt="CleanShot 2022-03-14 at 10 55 58@2x" src="https://user-images.githubusercontent.com/15965995/158148879-19b2ed9f-57d4-4690-82e4-ab5abce1dd3d.png">

I´ve tried several other configs but can´t get it to work
<img width="674" alt="CleanShot 2022-03-14 at 11 00 07@2x" src="https://user-images.githubusercontent.com/15965995/158149623-84ea5c8c-24a4-4095-a48c-9cb277344c01.png">

Maybe a Bug?

**Comment by rbswift** [comment]
This works well for me in a similar setup
     ```
   {
            "accessory": "mqttthing",
            "type": "temperatureSensor",
            "name": "Bathroom Temperature",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/mirrorheater/SENSOR",
                    "apply": "return (Math.round(JSON.parse(message).BME280.Temperature*2)/2);"
                }
            }
        },
```

**Comment by sommertrip** [comment]
Hi thx, but didn´t help
still receive the following message
[6.4.2022, 15:46:00] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by rbswift** [comment]
NaN means "not a number". Maybe you need to change the topic and BME280

**Comment by MDo3** [comment]
I was able to configure this sensor like this:

`{
   "accessory":"mqttthing",
   "type":"temperatureSensor",
   "name":"Temperature BLE Living room",
   "url":"mqtt://localhost",
   "topics":{
      "getCurrentTemperature":"tele/tasmota_D6376C/SENSOR$.LYWSD03c61721.Temperature",
      "getStatusLowBattery":"tele/tasmota_D6376C/SENSOR$.LYWSD03c61721.Battery"
       } },`


> Hi thx, but didn´t help still receive the following message [6.4.2022, 15:46:00] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by sommertrip** [comment]
Hi thx, did this according to your proposal, but do receive the following in the log files
[9.5.2022, 07:20:29] [Xiaomi BLE] Initializing mqttthing accessory...
[9.5.2022, 07:20:29] [Xiaomi BLE] Exception while creating services: TypeError: Cannot read properties of undefined (reading 'resubscribe')
[9.5.2022, 07:20:29] [Xiaomi BLE] TypeError: Cannot read properties of undefined (reading 'resubscribe')
    at MqttClient.subscribe (/usr/lib/node_modules/homebridge-mqttthing/node_modules/mqtt/lib/client.js:701:27)
    at Object.subscribe (/usr/lib/node_modules/homebridge-mqttthing/libs/mqttlib.js:325:24)
    at mqttSubscribe (/usr/lib/node_modules/homebridge-mqttthing/index.js:50:17)
    at floatCharacteristic (/usr/lib/node_modules/homebridge-mqttthing/index.js:1221:21)
    at characteristic_CurrentTemperature (/usr/lib/node_modules/homebridge-mqttthing/index.js:1593:17)
    at configToServices (/usr/lib/node_modules/homebridge-mqttthing/index.js:2846:17)
    at createServices (/usr/lib/node_modules/homebridge-mqttthing/index.js:3425:24)
    at new makeThing (/usr/lib/node_modules/homebridge-mqttthing/index.js:3457:23)
    at /usr/lib/node_modules/homebridge/src/server.ts:352:50
    at Array.forEach (<anonymous>)
[9.5.2022, 07:20:29] [Xiaomi BLE] Accessory mqttthing returned empty set of services; not adding it to the bridge.

**Comment by 2610** [comment]
You could try the the following as works for me.
I have LYWSD03MMC with modified firmware via  https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html , Advertising type set yo PVVX,
i have a ESP32 running Tasmota 32 Bluetooth, this detects the sensors then sends to mqtt i have set MI32Option6 1 so the each sensor gets a unique tele topic. i set this up as a rule so starts up on boot

    rule1 on system#boot do backlog MI32Option6 1; MI32Period 60 endon
    rule1 1

{
            "accessory": "mqttthing",
            "type": "weatherStation",
            "name": "XXXXXXXXX",
            "url": "mqtt://XXXXXXXX",
            "username": "XXXXXXX",
            "password": "XXXXXXX",
            "caption": "XXXXXXX",
            "mqttOptions": {
                "keepalive": 30
            },
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getCurrentTemperature": {
                    "topic": "tele/tasmota_ble/XXXXXXXX",
                    "apply": "return JSON.parse(message).Temperature"
                },
                "getCurrentRelativeHumidity": {
                    "topic": "tele/tasmota_ble/XXXXXXXX",
                    "apply": "return JSON.parse(message).Humidity"
                },
                "getDewPoint": {
                    "topic": "tele/tasmota_ble/XXXXXXXX",
                    "apply": "return JSON.parse(message).DewPoint"
                }
            },
            "history": "true",
            "manufacturer": "Xiaomi",
            "model": "LYWSD03MMC",
            "firmwareRevision": "XXXXXXXX"
}
Hopefully this works for you
