### ISSUE TITLE
Ignoring invalid value - type: "lightSensor"

### ISSUE THREAD

**Issue by JustAnotherIssue** [arachnetech/homebridge-mqttthing#556]
v1.4.1

Ignoring invalid value [**0**] for Current Ambient Light Level - below minimum (**0.0001**)

**Comment by knobby888** [comment]
Also having this issue it causes the light sensor reading to to freeze when the sensor reads 0

[6/1/2022, 10:24:27 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://homebridge.io/w/JtMGR for more info.
[6/1/2022, 10:24:27 PM] [homebridge-mqttthing] Error: 
    at CurrentAmbientLightLevel.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at CurrentAmbientLightLevel.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at handleGetStateCallback (/homebridge/node_modules/homebridge-mqttthing/index.js:282:21)
    at CurrentAmbientLightLevel.<anonymous> (/homebridge/node_modules/homebridge-mqttthing/index.js:1204:21)
    at CurrentAmbientLightLevel.emit (node:events:526:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at CurrentAmbientLightLevel.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at CurrentAmbientLightLevel.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1569:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)

**Comment by odelcourt** [comment]
Hi, it could be nice to update the maximum value (actually 100k) to 150k as the new weather station goes beyond the 100k Lumens.

**Comment by odelcourt** [comment]
* 120k seems more reasonable ;)

**Comment by odelcourt** [comment]
> * 120k seems more reasonable ;)

or not, I have seen more than 120k Lux this week at my home WS.
