### ISSUE TITLE
Expected `concurrency` to be a number from 1 and up 

### ISSUE THREAD

**Issue by alfital2** [arachnetech/homebridge-mqttthing#679]
Hi , even tough my config.json has concurrency > 1 (I tried 1/3/5/10 all failed):

{
    "bridge": {
        "name": "Homebridge BA3D",
        "username": "0E:F1:D3:85:BA:3D",
        "port": 51248,
        "pin": "1XXXXXXXX"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8581,
            "concurrency": 10,
            "log": {
                "method": "file",
                "path": "/data/data/com.termux/files/home/.homebridge/homebridge.log"
            }
        }
    ]
}

I get this in my logs: 

[7/24/2024, 3:07:45 PM] [Homebridge UI] Expected `concurrency` to be a number from 1 and up TypeError: Expected `concurrency` to be a number from 1 and up
    at pLimit (/data/data/com.termux/files/usr/lib/node_modules/homebridge-config-ui-x/node_modules/p-limit/index.js:6:9)
    at PluginsService.getInstalledPlugins (/data/data/com.termux/files/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:6756:23)
    at /data/data/com.termux/files/usr/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/core/router/router-proxy.js:9:17) ExceptionsHandler

and this is the error in th uI

×
Error
Failed to load plugins: Http failure response for http://192.168.0.179:8581/api/plugins: 500 Internal Server Error

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/17901a86-5765-4a1f-8c49-3b185efe42dc">

help please 🙏🏼

**Comment by alfital2** [comment]
> Got any solution??

No🥲

**Comment by TenelKa31** [comment]
Same issue on my side and here: https://github.com/Orachigami/homebridge-android/issues/1

Seems to be a quite frequent issue for Android users, any ideas on what to do?

**Comment by rbswift** [comment]
This doesn't look related to mqttthing. maybe post in the main homebridge project instead?
