### ISSUE TITLE
Compatibility with Homebridge 2.0

### ISSUE THREAD

**Issue by noelhibbard** [arachnetech/homebridge-mqttthing#681]
I just switched to 2.0-beta.11 and now I'm getting this error in the log:
```
TypeError: Service.BatteryService is not a constructor
    at configToServices (/homebridge/node_modules/homebridge-mqttthing/index.js:3545:34)
    at createServices (/homebridge/node_modules/homebridge-mqttthing/index.js:3568:24)
    at new makeThing (/homebridge/node_modules/homebridge-mqttthing/index.js:3600:23)
    at /homebridge/node_modules/homebridge/src/server.ts:362:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/homebridge/node_modules/homebridge/src/server.ts:282:29)
    at Server.start (/homebridge/node_modules/homebridge/src/server.ts:167:12)
```

Here is the config for the accessory that is throwing the error:
```json
        {
            "accessory": "mqttthing",
            "type": "contactSensor",
            "name": "Kitchen Refrigerator Door",
            "url": "mqtt://server1.example.com",
            "topics": {
                "getContactSensorState": {
                    "topic": "zigbee2mqtt/Kitchen/Fridge Door",
                    "apply": "return !JSON.parse(message).contact;"
                },
                "getStatusTampered": {
                    "topic": "zigbee2mqtt/Kitchen/Fridge Door",
                    "apply": "return JSON.parse(message).tamper;"
                },
                "getStatusLowBattery": {
                    "topic": "zigbee2mqtt/Kitchen/Fridge Door",
                    "apply": "return JSON.parse(message).battery_low;"
                },
                "getBatteryLevel": {
                    "topic": "zigbee2mqtt/Kitchen/Fridge Door",
                    "apply": "return JSON.parse(message).battery;"
                }
            }
        }
```

If I remove the config for ```getBatteryLevel```, this error goes away and everything seems to work fine.

**Comment by fox34** [comment]
Context, as stated in [the homebridge guide for upgrading to 2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0):

> `BatteryService` has been removed in favour of `Battery`

**Comment by GithHobby** [comment]
How did you switch to the beta? 
I'm using the 1.8.5 and I didn't find how to switch.

**Comment by TesterTi** [comment]
for my setup it seems to work but I receive the following exceptions for all my accessories, e.g.

[homebridge-z2m] Restoring accessory: Temperature Entrance (0x00XXXXXXXXXXXXXXX)
[homebridge-z2m] Exception occurred when creating services for Temperature Outdoors: TypeError: Cannot read properties of undefined (reading 'UUID')

**Comment by noelhibbard** [comment]
> for my setup it seems to work fine

As long as your config doesn't query battery status, it works fine.

**Comment by TesterTi** [comment]
True for this plugin but I use homebridge-zigbee2mqtt to bridge my zigbee network, which passes battery status without a problem in v2.

**Comment by noelhibbard** [comment]
> True (FYI: I use homebridge-zigbee2mqtt to bridge my zigbee network, which passes battery status without a problem in v2).

I've been meaning to check that plugin out. Thanks for the tip.
